# Uncomment the next line to define a global platform for your project
  platform :ios, '9.0'

target 'GankiOSer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Moya/RxSwift'
  pod 'RxDataSources'
  pod 'Action'
  pod 'Then'
  pod 'HandyJSON' 
  pod 'Kingfisher'
  pod 'MJRefresh'
  pod 'SwiftDate'
  pod 'IQKeyboardManager'
  pod 'SVProgressHUD'
  pod 'Hero'
  pod "CollectionKit"
  pod 'SideMenu'

end
